"""
Merge Engine — runs continuously while both buttons are off (idle reading).

Responsibilities:
1. Clean OCR text: fix grammar/OCR noise against 'Septopus: Trouble on the High Cs'
   by Jyotin Goel, and strip running headers/footers/page numbers.
2. Maintain dynamic memory across frames and page transitions.
3. Generates Python state code (`reading_state.py`) and word pointer map so
   the offline TTS engine knows its exact word index across pause/resume.
"""
import json
import logging
from pathlib import Path
import re
from typing import Dict, List, Optional

from config import settings
from ocr_memory import pipeline, merge_ocr_with_groq

log = logging.getLogger("taletrace.merge")

MEMORY_PATH = Path("reading_memory.json")
POINTER_MAP_PATH = Path("pointer_map.json")
PYTHON_STATE_PATH = Path("reading_state.py")


def clean_ocr_text(raw_text: str) -> str:
    """Cleans OCR noise and strips headers/footers against the Septopus book."""
    if not raw_text or not raw_text.strip():
        return ""
    # Strip headers/footers locally without making redundant duplicate API calls
    return _strip_obvious_headers(raw_text)


def display_merge_memory_terminal(text: str, current_word_idx: int = 0, total_words: int = 0) -> None:
    """Prints clear, nicely formatted active merge memory content to the terminal."""
    border = "=" * 70
    sub_border = "-" * 70
    content = text.strip() if text and text.strip() else "[EMPTY / NO BOOK TEXT IN MEMORY]"
    
    print(f"\n{border}")
    print(f"📖 [ACTIVE MERGE MEMORY CONTENT] (Total Words: {total_words})")
    print(sub_border)
    print(content)
    print(sub_border)
    print(f"📍 Active Reading Pointer: Word #{current_word_idx}")
    print(f"{border}\n")


def _strip_obvious_headers(text: str) -> str:
    """Regex fallback to strip stray page numbers or uppercase running headers."""
    lines = text.splitlines()
    out = []
    for line in lines:
        stripped = line.strip()
        if re.fullmatch(r"\d{1,4}", stripped):
            continue  # standalone page number
        if len(stripped) <= 40 and stripped.isupper():
            continue  # uppercase running header
        out.append(line)
    return "\n".join(out).strip()


def build_word_pointer_map(text: str) -> List[Dict]:
    """Builds word-level character offset map: [{'w': word, 'start': int, 'end': int}]."""
    words = []
    for m in re.finditer(r"\S+", text):
        words.append({
            "w": m.group(0),
            "start": m.start(),
            "end": m.end(),
        })
    return words


def generate_python_code_state(
    book_title: str,
    merged_text: str,
    word_map: List[Dict],
    current_word_idx: int = 0,
    current_char_offset: int = 0,
) -> str:
    """
    Generates executable Python state code (reading_state.py) as required by spec,
    so that TTS reading pointer remains strictly correct across pauses and updates.
    """
    escaped_text = merged_text.replace('\\', '\\\\').replace('"', '\\"').replace("'''", "\\'\\'\\'")
    code = f'''# -*- coding: utf-8 -*-
"""
Auto-generated reading state module for TaleTrace.
Generated by Groq Memory Engine to track and preserve the active reading pointer.
"""

BOOK_TITLE = "{book_title}"
CURRENT_WORD_INDEX = {current_word_idx}
CURRENT_CHAR_OFFSET = {current_char_offset}

MERGED_TEXT = """{escaped_text}"""

WORDS = {json.dumps(word_map, ensure_ascii=False, indent=2)}


def get_word_at_offset(char_offset: int) -> int:
    """Finds word index corresponding to character offset in MERGED_TEXT."""
    for i, w in enumerate(WORDS):
        if w["start"] <= char_offset < w["end"]:
            return i
    return -1


def get_next_word_index(current_idx: int) -> int:
    """Returns next word index, bounded by total word count."""
    if current_idx + 1 < len(WORDS):
        return current_idx + 1
    return len(WORDS) - 1
'''
    return code


def update_memory_and_pointer_map(cleaned_page_text: str, current_speaking_word_index: int = 0) -> Dict:
    """
    Merges cleaned page text into active memory using TaleTraceMemoryManager,
    reconciles pointers, and exports reading_state.py and pointer_map.json.
    """
    # 1. Update text via memory manager pipeline
    updated_memory = pipeline.process_ocr_text(cleaned_page_text)

    # 2. Build word pointer list
    words = build_word_pointer_map(updated_memory)
    pointer_map = {"words": words}

    # 3. Preserve the current speaking word index unless a page transition occurred
    word_idx = min(current_speaking_word_index, max(0, len(words) - 1)) if words else 0
    char_offset = words[word_idx]["start"] if words and word_idx < len(words) else 0

    # 4. Generate Python state code
    python_code = generate_python_code_state(
        book_title=settings.book_title,
        merged_text=updated_memory,
        word_map=words,
        current_word_idx=word_idx,
        current_char_offset=char_offset,
    )
    PYTHON_STATE_PATH.write_text(python_code, encoding="utf-8")

    # 5. Save JSON mirrors for backward compatibility
    MEMORY_PATH.write_text(json.dumps({"text": updated_memory}, ensure_ascii=False, indent=2), encoding="utf-8")
    POINTER_MAP_PATH.write_text(json.dumps(pointer_map, ensure_ascii=False, indent=2), encoding="utf-8")

    log.info(
        "Memory updated: %d total words. Reading state saved to %s",
        len(words),
        PYTHON_STATE_PATH.name,
    )
    # Display the exact content in terminal as requested
    display_merge_memory_terminal(updated_memory, current_word_idx=word_idx, total_words=len(words))
    return pointer_map


def get_memory_text() -> str:
    if MEMORY_PATH.exists():
        try:
            return json.loads(MEMORY_PATH.read_text(encoding="utf-8")).get("text", "")
        except Exception:
            pass
    return pipeline.merge_memory


def get_pointer_map() -> Dict:
    if POINTER_MAP_PATH.exists():
        try:
            return json.loads(POINTER_MAP_PATH.read_text(encoding="utf-8"))
        except Exception:
            pass
    return {"words": []}


def get_memory_text_up_to(word_index: int, include_prior_sessions: bool = True) -> str:
    """
    Returns all read text strictly up to and including word_index (no forward spoilers),
    joining prior session pages and the current page slice.
    """
    prior_slices: List[str] = []
    if include_prior_sessions and hasattr(pipeline, "permanent_memory"):
        for page in pipeline.permanent_memory:
            if page and page.strip():
                prior_slices.append(page.strip())

    current_page_text = get_memory_text().strip()
    current_slice = ""
    if current_page_text:
        words = build_word_pointer_map(current_page_text)
        if words and word_index >= 0:
            if word_index < len(words):
                end_char = words[word_index]["end"]
                current_slice = current_page_text[:end_char].strip()
            else:
                current_slice = current_page_text
        else:
            current_slice = current_page_text

    if current_slice:
        prior_slices.append(current_slice)

    return "\n\n".join(prior_slices).strip()


def recap_up_to(word_index: int, max_lines: int = 5, include_prior_sessions: bool = True) -> str:
    """
    Collects past read text strictly up to current word_index (no forward spoilers),
    optionally including archived pages from prior sessions, and returns a 4-5 line recap.
    """
    from ai_engine import generate_recap

    combined_text = get_memory_text_up_to(word_index, include_prior_sessions=include_prior_sessions)
    if not combined_text:
        return "No text has been read so far to recap."

    return generate_recap(combined_text, max_lines=max_lines)

