# -*- coding: utf-8 -*-
"""
Auto-generated reading state module for TaleTrace.
Generated by Groq Memory Engine to track and preserve the active reading pointer.
"""

BOOK_TITLE = "Septopus: Trouble on the High Cs"
CURRENT_WORD_INDEX = 70
CURRENT_CHAR_OFFSET = 363

MERGED_TEXT = """The was, breathing normally; a tree with Tumboo! Well right now, Tumboo? replied. “Full of air like a balloon!” noticed. Rot8 but I'm sometimes had a grin). But right. at her. Of course it was odd, strange, at was even more peculiar was the St. was also a part of this. He knew could survive only a few minutes out e was, B breathing normally hoo!
as Rot let the air out of the inflatable fin.
\"You. you...
: Irrit gasped but, like Po, he
out of the breath needed to express his feel
'Shove him into the water, Tumbs, R
still laughing. 'Let them get some oxygen in
gills:
\"Остор, you know, bars n
That songs going to be for h
Tumboo guffawed and In
as Rot let the air our of the
You.. you. Irrit gasped"""

WORDS = [
  {
    "w": "The",
    "start": 0,
    "end": 3
  },
  {
    "w": "was,",
    "start": 4,
    "end": 8
  },
  {
    "w": "breathing",
    "start": 9,
    "end": 18
  },
  {
    "w": "normally;",
    "start": 19,
    "end": 28
  },
  {
    "w": "a",
    "start": 29,
    "end": 30
  },
  {
    "w": "tree",
    "start": 31,
    "end": 35
  },
  {
    "w": "with",
    "start": 36,
    "end": 40
  },
  {
    "w": "Tumboo!",
    "start": 41,
    "end": 48
  },
  {
    "w": "Well",
    "start": 49,
    "end": 53
  },
  {
    "w": "right",
    "start": 54,
    "end": 59
  },
  {
    "w": "now,",
    "start": 60,
    "end": 64
  },
  {
    "w": "Tumboo?",
    "start": 65,
    "end": 72
  },
  {
    "w": "replied.",
    "start": 73,
    "end": 81
  },
  {
    "w": "“Full",
    "start": 82,
    "end": 87
  },
  {
    "w": "of",
    "start": 88,
    "end": 90
  },
  {
    "w": "air",
    "start": 91,
    "end": 94
  },
  {
    "w": "like",
    "start": 95,
    "end": 99
  },
  {
    "w": "a",
    "start": 100,
    "end": 101
  },
  {
    "w": "balloon!”",
    "start": 102,
    "end": 111
  },
  {
    "w": "noticed.",
    "start": 112,
    "end": 120
  },
  {
    "w": "Rot8",
    "start": 121,
    "end": 125
  },
  {
    "w": "but",
    "start": 126,
    "end": 129
  },
  {
    "w": "I'm",
    "start": 130,
    "end": 133
  },
  {
    "w": "sometimes",
    "start": 134,
    "end": 143
  },
  {
    "w": "had",
    "start": 144,
    "end": 147
  },
  {
    "w": "a",
    "start": 148,
    "end": 149
  },
  {
    "w": "grin).",
    "start": 150,
    "end": 156
  },
  {
    "w": "But",
    "start": 157,
    "end": 160
  },
  {
    "w": "right.",
    "start": 161,
    "end": 167
  },
  {
    "w": "at",
    "start": 168,
    "end": 170
  },
  {
    "w": "her.",
    "start": 171,
    "end": 175
  },
  {
    "w": "Of",
    "start": 176,
    "end": 178
  },
  {
    "w": "course",
    "start": 179,
    "end": 185
  },
  {
    "w": "it",
    "start": 186,
    "end": 188
  },
  {
    "w": "was",
    "start": 189,
    "end": 192
  },
  {
    "w": "odd,",
    "start": 193,
    "end": 197
  },
  {
    "w": "strange,",
    "start": 198,
    "end": 206
  },
  {
    "w": "at",
    "start": 207,
    "end": 209
  },
  {
    "w": "was",
    "start": 210,
    "end": 213
  },
  {
    "w": "even",
    "start": 214,
    "end": 218
  },
  {
    "w": "more",
    "start": 219,
    "end": 223
  },
  {
    "w": "peculiar",
    "start": 224,
    "end": 232
  },
  {
    "w": "was",
    "start": 233,
    "end": 236
  },
  {
    "w": "the",
    "start": 237,
    "end": 240
  },
  {
    "w": "St.",
    "start": 241,
    "end": 244
  },
  {
    "w": "was",
    "start": 245,
    "end": 248
  },
  {
    "w": "also",
    "start": 249,
    "end": 253
  },
  {
    "w": "a",
    "start": 254,
    "end": 255
  },
  {
    "w": "part",
    "start": 256,
    "end": 260
  },
  {
    "w": "of",
    "start": 261,
    "end": 263
  },
  {
    "w": "this.",
    "start": 264,
    "end": 269
  },
  {
    "w": "He",
    "start": 270,
    "end": 272
  },
  {
    "w": "knew",
    "start": 273,
    "end": 277
  },
  {
    "w": "could",
    "start": 278,
    "end": 283
  },
  {
    "w": "survive",
    "start": 284,
    "end": 291
  },
  {
    "w": "only",
    "start": 292,
    "end": 296
  },
  {
    "w": "a",
    "start": 297,
    "end": 298
  },
  {
    "w": "few",
    "start": 299,
    "end": 302
  },
  {
    "w": "minutes",
    "start": 303,
    "end": 310
  },
  {
    "w": "out",
    "start": 311,
    "end": 314
  },
  {
    "w": "e",
    "start": 315,
    "end": 316
  },
  {
    "w": "was,",
    "start": 317,
    "end": 321
  },
  {
    "w": "B",
    "start": 322,
    "end": 323
  },
  {
    "w": "breathing",
    "start": 324,
    "end": 333
  },
  {
    "w": "normally",
    "start": 334,
    "end": 342
  },
  {
    "w": "hoo!",
    "start": 343,
    "end": 347
  },
  {
    "w": "as",
    "start": 348,
    "end": 350
  },
  {
    "w": "Rot",
    "start": 351,
    "end": 354
  },
  {
    "w": "let",
    "start": 355,
    "end": 358
  },
  {
    "w": "the",
    "start": 359,
    "end": 362
  },
  {
    "w": "air",
    "start": 363,
    "end": 366
  },
  {
    "w": "out",
    "start": 367,
    "end": 370
  },
  {
    "w": "of",
    "start": 371,
    "end": 373
  },
  {
    "w": "the",
    "start": 374,
    "end": 377
  },
  {
    "w": "inflatable",
    "start": 378,
    "end": 388
  },
  {
    "w": "fin.",
    "start": 389,
    "end": 393
  },
  {
    "w": "\"You.",
    "start": 394,
    "end": 399
  },
  {
    "w": "you...",
    "start": 400,
    "end": 406
  },
  {
    "w": ":",
    "start": 407,
    "end": 408
  },
  {
    "w": "Irrit",
    "start": 409,
    "end": 414
  },
  {
    "w": "gasped",
    "start": 415,
    "end": 421
  },
  {
    "w": "but,",
    "start": 422,
    "end": 426
  },
  {
    "w": "like",
    "start": 427,
    "end": 431
  },
  {
    "w": "Po,",
    "start": 432,
    "end": 435
  },
  {
    "w": "he",
    "start": 436,
    "end": 438
  },
  {
    "w": "out",
    "start": 439,
    "end": 442
  },
  {
    "w": "of",
    "start": 443,
    "end": 445
  },
  {
    "w": "the",
    "start": 446,
    "end": 449
  },
  {
    "w": "breath",
    "start": 450,
    "end": 456
  },
  {
    "w": "needed",
    "start": 457,
    "end": 463
  },
  {
    "w": "to",
    "start": 464,
    "end": 466
  },
  {
    "w": "express",
    "start": 467,
    "end": 474
  },
  {
    "w": "his",
    "start": 475,
    "end": 478
  },
  {
    "w": "feel",
    "start": 479,
    "end": 483
  },
  {
    "w": "'Shove",
    "start": 484,
    "end": 490
  },
  {
    "w": "him",
    "start": 491,
    "end": 494
  },
  {
    "w": "into",
    "start": 495,
    "end": 499
  },
  {
    "w": "the",
    "start": 500,
    "end": 503
  },
  {
    "w": "water,",
    "start": 504,
    "end": 510
  },
  {
    "w": "Tumbs,",
    "start": 511,
    "end": 517
  },
  {
    "w": "R",
    "start": 518,
    "end": 519
  },
  {
    "w": "still",
    "start": 520,
    "end": 525
  },
  {
    "w": "laughing.",
    "start": 526,
    "end": 535
  },
  {
    "w": "'Let",
    "start": 536,
    "end": 540
  },
  {
    "w": "them",
    "start": 541,
    "end": 545
  },
  {
    "w": "get",
    "start": 546,
    "end": 549
  },
  {
    "w": "some",
    "start": 550,
    "end": 554
  },
  {
    "w": "oxygen",
    "start": 555,
    "end": 561
  },
  {
    "w": "in",
    "start": 562,
    "end": 564
  },
  {
    "w": "gills:",
    "start": 565,
    "end": 571
  },
  {
    "w": "\"Остор,",
    "start": 572,
    "end": 579
  },
  {
    "w": "you",
    "start": 580,
    "end": 583
  },
  {
    "w": "know,",
    "start": 584,
    "end": 589
  },
  {
    "w": "bars",
    "start": 590,
    "end": 594
  },
  {
    "w": "n",
    "start": 595,
    "end": 596
  },
  {
    "w": "That",
    "start": 597,
    "end": 601
  },
  {
    "w": "songs",
    "start": 602,
    "end": 607
  },
  {
    "w": "going",
    "start": 608,
    "end": 613
  },
  {
    "w": "to",
    "start": 614,
    "end": 616
  },
  {
    "w": "be",
    "start": 617,
    "end": 619
  },
  {
    "w": "for",
    "start": 620,
    "end": 623
  },
  {
    "w": "h",
    "start": 624,
    "end": 625
  },
  {
    "w": "Tumboo",
    "start": 626,
    "end": 632
  },
  {
    "w": "guffawed",
    "start": 633,
    "end": 641
  },
  {
    "w": "and",
    "start": 642,
    "end": 645
  },
  {
    "w": "In",
    "start": 646,
    "end": 648
  },
  {
    "w": "as",
    "start": 649,
    "end": 651
  },
  {
    "w": "Rot",
    "start": 652,
    "end": 655
  },
  {
    "w": "let",
    "start": 656,
    "end": 659
  },
  {
    "w": "the",
    "start": 660,
    "end": 663
  },
  {
    "w": "air",
    "start": 664,
    "end": 667
  },
  {
    "w": "our",
    "start": 668,
    "end": 671
  },
  {
    "w": "of",
    "start": 672,
    "end": 674
  },
  {
    "w": "the",
    "start": 675,
    "end": 678
  },
  {
    "w": "You..",
    "start": 679,
    "end": 684
  },
  {
    "w": "you.",
    "start": 685,
    "end": 689
  },
  {
    "w": "Irrit",
    "start": 690,
    "end": 695
  },
  {
    "w": "gasped",
    "start": 696,
    "end": 702
  }
]


def get_word_at_offset(char_offset: int) -> int:
    """Finds word index corresponding to character offset in MERGED_TEXT."""
    for i, w in enumerate(WORDS):
        if w["start"] <= char_offset < w["end"]:
            return i
    return -1


def get_next_word_index(current_idx: int) -> int:
    """Returns next word index, bounded by total word count."""
    if current_idx + 1 < len(WORDS):
        return current_idx + 1
    return len(WORDS) - 1
