# -*- coding: utf-8 -*-
"""
Auto-generated reading state module for TaleTrace.
Generated by Groq Memory Engine to track and preserve the active reading pointer.
"""

BOOK_TITLE = "Septopus: Trouble on the High Cs"
CURRENT_WORD_INDEX = 138
CURRENT_CHAR_OFFSET = 772

MERGED_TEXT = """Sweeping the spilled food into one pile, he carried the mixture to the tank and tossed it into the water. “All yours, you stinkin’ slugs!” he said rudely to Rot8 and Tumboo. Then, whistling a carefree tune, he turned the jars upright and wheeled the vacuum cleaner out of the lab. “Finally!” exclaimed Tumboo, hungrily eyeing the food that the worker had dropped into their tank. “Let’s dig in, Rot8,” Tumboo said. “I’m not sure we should, Tumboo,” Rot8 replied. “The Lab Lady usually pours food in just one jar at a time!” “She’s not here, Rot8! And the food is…” Tumboo purred a virtuous air. With so many fish going hungry, is it right to waste food? Rot8 grinned. The four‑food mixture gave off a rare, lingering smell. It was not pleasant. Rot8 snapped a quick bite. The four‑food mixture smelled strange and unpleasant. Rot8 snapped a spoon onto the lily pad and sampled the mixed‑up food gingerly."""

WORDS = [
  {
    "w": "Sweeping",
    "start": 0,
    "end": 8
  },
  {
    "w": "the",
    "start": 9,
    "end": 12
  },
  {
    "w": "spilled",
    "start": 13,
    "end": 20
  },
  {
    "w": "food",
    "start": 21,
    "end": 25
  },
  {
    "w": "into",
    "start": 26,
    "end": 30
  },
  {
    "w": "one",
    "start": 31,
    "end": 34
  },
  {
    "w": "pile,",
    "start": 35,
    "end": 40
  },
  {
    "w": "he",
    "start": 41,
    "end": 43
  },
  {
    "w": "carried",
    "start": 44,
    "end": 51
  },
  {
    "w": "the",
    "start": 52,
    "end": 55
  },
  {
    "w": "mixture",
    "start": 56,
    "end": 63
  },
  {
    "w": "to",
    "start": 64,
    "end": 66
  },
  {
    "w": "the",
    "start": 67,
    "end": 70
  },
  {
    "w": "tank",
    "start": 71,
    "end": 75
  },
  {
    "w": "and",
    "start": 76,
    "end": 79
  },
  {
    "w": "tossed",
    "start": 80,
    "end": 86
  },
  {
    "w": "it",
    "start": 87,
    "end": 89
  },
  {
    "w": "into",
    "start": 90,
    "end": 94
  },
  {
    "w": "the",
    "start": 95,
    "end": 98
  },
  {
    "w": "water.",
    "start": 99,
    "end": 105
  },
  {
    "w": "“All",
    "start": 106,
    "end": 110
  },
  {
    "w": "yours,",
    "start": 111,
    "end": 117
  },
  {
    "w": "you",
    "start": 118,
    "end": 121
  },
  {
    "w": "stinkin’",
    "start": 122,
    "end": 130
  },
  {
    "w": "slugs!”",
    "start": 131,
    "end": 138
  },
  {
    "w": "he",
    "start": 139,
    "end": 141
  },
  {
    "w": "said",
    "start": 142,
    "end": 146
  },
  {
    "w": "rudely",
    "start": 147,
    "end": 153
  },
  {
    "w": "to",
    "start": 154,
    "end": 156
  },
  {
    "w": "Rot8",
    "start": 157,
    "end": 161
  },
  {
    "w": "and",
    "start": 162,
    "end": 165
  },
  {
    "w": "Tumboo.",
    "start": 166,
    "end": 173
  },
  {
    "w": "Then,",
    "start": 174,
    "end": 179
  },
  {
    "w": "whistling",
    "start": 180,
    "end": 189
  },
  {
    "w": "a",
    "start": 190,
    "end": 191
  },
  {
    "w": "carefree",
    "start": 192,
    "end": 200
  },
  {
    "w": "tune,",
    "start": 201,
    "end": 206
  },
  {
    "w": "he",
    "start": 207,
    "end": 209
  },
  {
    "w": "turned",
    "start": 210,
    "end": 216
  },
  {
    "w": "the",
    "start": 217,
    "end": 220
  },
  {
    "w": "jars",
    "start": 221,
    "end": 225
  },
  {
    "w": "upright",
    "start": 226,
    "end": 233
  },
  {
    "w": "and",
    "start": 234,
    "end": 237
  },
  {
    "w": "wheeled",
    "start": 238,
    "end": 245
  },
  {
    "w": "the",
    "start": 246,
    "end": 249
  },
  {
    "w": "vacuum",
    "start": 250,
    "end": 256
  },
  {
    "w": "cleaner",
    "start": 257,
    "end": 264
  },
  {
    "w": "out",
    "start": 265,
    "end": 268
  },
  {
    "w": "of",
    "start": 269,
    "end": 271
  },
  {
    "w": "the",
    "start": 272,
    "end": 275
  },
  {
    "w": "lab.",
    "start": 276,
    "end": 280
  },
  {
    "w": "“Finally!”",
    "start": 281,
    "end": 291
  },
  {
    "w": "exclaimed",
    "start": 292,
    "end": 301
  },
  {
    "w": "Tumboo,",
    "start": 302,
    "end": 309
  },
  {
    "w": "hungrily",
    "start": 310,
    "end": 318
  },
  {
    "w": "eyeing",
    "start": 319,
    "end": 325
  },
  {
    "w": "the",
    "start": 326,
    "end": 329
  },
  {
    "w": "food",
    "start": 330,
    "end": 334
  },
  {
    "w": "that",
    "start": 335,
    "end": 339
  },
  {
    "w": "the",
    "start": 340,
    "end": 343
  },
  {
    "w": "worker",
    "start": 344,
    "end": 350
  },
  {
    "w": "had",
    "start": 351,
    "end": 354
  },
  {
    "w": "dropped",
    "start": 355,
    "end": 362
  },
  {
    "w": "into",
    "start": 363,
    "end": 367
  },
  {
    "w": "their",
    "start": 368,
    "end": 373
  },
  {
    "w": "tank.",
    "start": 374,
    "end": 379
  },
  {
    "w": "“Let’s",
    "start": 380,
    "end": 386
  },
  {
    "w": "dig",
    "start": 387,
    "end": 390
  },
  {
    "w": "in,",
    "start": 391,
    "end": 394
  },
  {
    "w": "Rot8,”",
    "start": 395,
    "end": 401
  },
  {
    "w": "Tumboo",
    "start": 402,
    "end": 408
  },
  {
    "w": "said.",
    "start": 409,
    "end": 414
  },
  {
    "w": "“I’m",
    "start": 415,
    "end": 419
  },
  {
    "w": "not",
    "start": 420,
    "end": 423
  },
  {
    "w": "sure",
    "start": 424,
    "end": 428
  },
  {
    "w": "we",
    "start": 429,
    "end": 431
  },
  {
    "w": "should,",
    "start": 432,
    "end": 439
  },
  {
    "w": "Tumboo,”",
    "start": 440,
    "end": 448
  },
  {
    "w": "Rot8",
    "start": 449,
    "end": 453
  },
  {
    "w": "replied.",
    "start": 454,
    "end": 462
  },
  {
    "w": "“The",
    "start": 463,
    "end": 467
  },
  {
    "w": "Lab",
    "start": 468,
    "end": 471
  },
  {
    "w": "Lady",
    "start": 472,
    "end": 476
  },
  {
    "w": "usually",
    "start": 477,
    "end": 484
  },
  {
    "w": "pours",
    "start": 485,
    "end": 490
  },
  {
    "w": "food",
    "start": 491,
    "end": 495
  },
  {
    "w": "in",
    "start": 496,
    "end": 498
  },
  {
    "w": "just",
    "start": 499,
    "end": 503
  },
  {
    "w": "one",
    "start": 504,
    "end": 507
  },
  {
    "w": "jar",
    "start": 508,
    "end": 511
  },
  {
    "w": "at",
    "start": 512,
    "end": 514
  },
  {
    "w": "a",
    "start": 515,
    "end": 516
  },
  {
    "w": "time!”",
    "start": 517,
    "end": 523
  },
  {
    "w": "“She’s",
    "start": 524,
    "end": 530
  },
  {
    "w": "not",
    "start": 531,
    "end": 534
  },
  {
    "w": "here,",
    "start": 535,
    "end": 540
  },
  {
    "w": "Rot8!",
    "start": 541,
    "end": 546
  },
  {
    "w": "And",
    "start": 547,
    "end": 550
  },
  {
    "w": "the",
    "start": 551,
    "end": 554
  },
  {
    "w": "food",
    "start": 555,
    "end": 559
  },
  {
    "w": "is…”",
    "start": 560,
    "end": 564
  },
  {
    "w": "Tumboo",
    "start": 565,
    "end": 571
  },
  {
    "w": "purred",
    "start": 572,
    "end": 578
  },
  {
    "w": "a",
    "start": 579,
    "end": 580
  },
  {
    "w": "virtuous",
    "start": 581,
    "end": 589
  },
  {
    "w": "air.",
    "start": 590,
    "end": 594
  },
  {
    "w": "With",
    "start": 595,
    "end": 599
  },
  {
    "w": "so",
    "start": 600,
    "end": 602
  },
  {
    "w": "many",
    "start": 603,
    "end": 607
  },
  {
    "w": "fish",
    "start": 608,
    "end": 612
  },
  {
    "w": "going",
    "start": 613,
    "end": 618
  },
  {
    "w": "hungry,",
    "start": 619,
    "end": 626
  },
  {
    "w": "is",
    "start": 627,
    "end": 629
  },
  {
    "w": "it",
    "start": 630,
    "end": 632
  },
  {
    "w": "right",
    "start": 633,
    "end": 638
  },
  {
    "w": "to",
    "start": 639,
    "end": 641
  },
  {
    "w": "waste",
    "start": 642,
    "end": 647
  },
  {
    "w": "food?",
    "start": 648,
    "end": 653
  },
  {
    "w": "Rot8",
    "start": 654,
    "end": 658
  },
  {
    "w": "grinned.",
    "start": 659,
    "end": 667
  },
  {
    "w": "The",
    "start": 668,
    "end": 671
  },
  {
    "w": "four‑food",
    "start": 672,
    "end": 681
  },
  {
    "w": "mixture",
    "start": 682,
    "end": 689
  },
  {
    "w": "gave",
    "start": 690,
    "end": 694
  },
  {
    "w": "off",
    "start": 695,
    "end": 698
  },
  {
    "w": "a",
    "start": 699,
    "end": 700
  },
  {
    "w": "rare,",
    "start": 701,
    "end": 706
  },
  {
    "w": "lingering",
    "start": 707,
    "end": 716
  },
  {
    "w": "smell.",
    "start": 717,
    "end": 723
  },
  {
    "w": "It",
    "start": 724,
    "end": 726
  },
  {
    "w": "was",
    "start": 727,
    "end": 730
  },
  {
    "w": "not",
    "start": 731,
    "end": 734
  },
  {
    "w": "pleasant.",
    "start": 735,
    "end": 744
  },
  {
    "w": "Rot8",
    "start": 745,
    "end": 749
  },
  {
    "w": "snapped",
    "start": 750,
    "end": 757
  },
  {
    "w": "a",
    "start": 758,
    "end": 759
  },
  {
    "w": "quick",
    "start": 760,
    "end": 765
  },
  {
    "w": "bite.",
    "start": 766,
    "end": 771
  },
  {
    "w": "The",
    "start": 772,
    "end": 775
  },
  {
    "w": "four‑food",
    "start": 776,
    "end": 785
  },
  {
    "w": "mixture",
    "start": 786,
    "end": 793
  },
  {
    "w": "smelled",
    "start": 794,
    "end": 801
  },
  {
    "w": "strange",
    "start": 802,
    "end": 809
  },
  {
    "w": "and",
    "start": 810,
    "end": 813
  },
  {
    "w": "unpleasant.",
    "start": 814,
    "end": 825
  },
  {
    "w": "Rot8",
    "start": 826,
    "end": 830
  },
  {
    "w": "snapped",
    "start": 831,
    "end": 838
  },
  {
    "w": "a",
    "start": 839,
    "end": 840
  },
  {
    "w": "spoon",
    "start": 841,
    "end": 846
  },
  {
    "w": "onto",
    "start": 847,
    "end": 851
  },
  {
    "w": "the",
    "start": 852,
    "end": 855
  },
  {
    "w": "lily",
    "start": 856,
    "end": 860
  },
  {
    "w": "pad",
    "start": 861,
    "end": 864
  },
  {
    "w": "and",
    "start": 865,
    "end": 868
  },
  {
    "w": "sampled",
    "start": 869,
    "end": 876
  },
  {
    "w": "the",
    "start": 877,
    "end": 880
  },
  {
    "w": "mixed‑up",
    "start": 881,
    "end": 889
  },
  {
    "w": "food",
    "start": 890,
    "end": 894
  },
  {
    "w": "gingerly.",
    "start": 895,
    "end": 904
  }
]


def get_word_at_offset(char_offset: int) -> int:
    """Finds word index corresponding to character offset in MERGED_TEXT."""
    for i, w in enumerate(WORDS):
        if w["start"] <= char_offset < w["end"]:
            return i
    return -1


def get_next_word_index(current_idx: int) -> int:
    """Returns next word index, bounded by total word count."""
    if current_idx + 1 < len(WORDS):
        return current_idx + 1
    return len(WORDS) - 1
