# -*- coding: utf-8 -*-
"""
Auto-generated reading state module for TaleTrace.
Generated by Groq Memory Engine to track and preserve the active reading pointer.
"""

BOOK_TITLE = "Septopus: Trouble on the High Cs"
CURRENT_WORD_INDEX = 54
CURRENT_CHAR_OFFSET = 264

MERGED_TEXT = """s be the his al the th rd and lock sauded. them yer some sy
nd Irris wasced in dishclief
A die inflatable far.
asped bus, like Po, he had run
ded to express his feelings.
the water, Tumbs, Rot said,
em get some oxygen into their
touch, if I say so myself, grinned Tumboo.
id did you ger those lyrics? Rot hooted
ow, bave no bones! Sheer genius?
the to con the son
mate co
Like P
Ten gaspet bac like to, he had tum
each needed to express his feelings.
sam into the water, Tumbs, Rot said
r some oxygen into their
nice touch, if I say so myself grinned Tambon
..and did you get chose lose Rot boorst
buses, you knem, bave me benes!\" Sheee genius!
ong's going to be the bit of the showt
nboo guffawed and hit watched in dickelet
let thé dir out of the taffatable ho
asped but tike Ba
Had fan
at Rot h
some Sheer senten
get those lyrics? Rot hooted.
W, have no bones\" Sheer genius!
, be the hit of the show!
a Tri watched in disbelief"""

WORDS = [
  {
    "w": "s",
    "start": 0,
    "end": 1
  },
  {
    "w": "be",
    "start": 2,
    "end": 4
  },
  {
    "w": "the",
    "start": 5,
    "end": 8
  },
  {
    "w": "his",
    "start": 9,
    "end": 12
  },
  {
    "w": "al",
    "start": 13,
    "end": 15
  },
  {
    "w": "the",
    "start": 16,
    "end": 19
  },
  {
    "w": "th",
    "start": 20,
    "end": 22
  },
  {
    "w": "rd",
    "start": 23,
    "end": 25
  },
  {
    "w": "and",
    "start": 26,
    "end": 29
  },
  {
    "w": "lock",
    "start": 30,
    "end": 34
  },
  {
    "w": "sauded.",
    "start": 35,
    "end": 42
  },
  {
    "w": "them",
    "start": 43,
    "end": 47
  },
  {
    "w": "yer",
    "start": 48,
    "end": 51
  },
  {
    "w": "some",
    "start": 52,
    "end": 56
  },
  {
    "w": "sy",
    "start": 57,
    "end": 59
  },
  {
    "w": "nd",
    "start": 60,
    "end": 62
  },
  {
    "w": "Irris",
    "start": 63,
    "end": 68
  },
  {
    "w": "wasced",
    "start": 69,
    "end": 75
  },
  {
    "w": "in",
    "start": 76,
    "end": 78
  },
  {
    "w": "dishclief",
    "start": 79,
    "end": 88
  },
  {
    "w": "A",
    "start": 89,
    "end": 90
  },
  {
    "w": "die",
    "start": 91,
    "end": 94
  },
  {
    "w": "inflatable",
    "start": 95,
    "end": 105
  },
  {
    "w": "far.",
    "start": 106,
    "end": 110
  },
  {
    "w": "asped",
    "start": 111,
    "end": 116
  },
  {
    "w": "bus,",
    "start": 117,
    "end": 121
  },
  {
    "w": "like",
    "start": 122,
    "end": 126
  },
  {
    "w": "Po,",
    "start": 127,
    "end": 130
  },
  {
    "w": "he",
    "start": 131,
    "end": 133
  },
  {
    "w": "had",
    "start": 134,
    "end": 137
  },
  {
    "w": "run",
    "start": 138,
    "end": 141
  },
  {
    "w": "ded",
    "start": 142,
    "end": 145
  },
  {
    "w": "to",
    "start": 146,
    "end": 148
  },
  {
    "w": "express",
    "start": 149,
    "end": 156
  },
  {
    "w": "his",
    "start": 157,
    "end": 160
  },
  {
    "w": "feelings.",
    "start": 161,
    "end": 170
  },
  {
    "w": "the",
    "start": 171,
    "end": 174
  },
  {
    "w": "water,",
    "start": 175,
    "end": 181
  },
  {
    "w": "Tumbs,",
    "start": 182,
    "end": 188
  },
  {
    "w": "Rot",
    "start": 189,
    "end": 192
  },
  {
    "w": "said,",
    "start": 193,
    "end": 198
  },
  {
    "w": "em",
    "start": 199,
    "end": 201
  },
  {
    "w": "get",
    "start": 202,
    "end": 205
  },
  {
    "w": "some",
    "start": 206,
    "end": 210
  },
  {
    "w": "oxygen",
    "start": 211,
    "end": 217
  },
  {
    "w": "into",
    "start": 218,
    "end": 222
  },
  {
    "w": "their",
    "start": 223,
    "end": 228
  },
  {
    "w": "touch,",
    "start": 229,
    "end": 235
  },
  {
    "w": "if",
    "start": 236,
    "end": 238
  },
  {
    "w": "I",
    "start": 239,
    "end": 240
  },
  {
    "w": "say",
    "start": 241,
    "end": 244
  },
  {
    "w": "so",
    "start": 245,
    "end": 247
  },
  {
    "w": "myself,",
    "start": 248,
    "end": 255
  },
  {
    "w": "grinned",
    "start": 256,
    "end": 263
  },
  {
    "w": "Tumboo.",
    "start": 264,
    "end": 271
  },
  {
    "w": "id",
    "start": 272,
    "end": 274
  },
  {
    "w": "did",
    "start": 275,
    "end": 278
  },
  {
    "w": "you",
    "start": 279,
    "end": 282
  },
  {
    "w": "ger",
    "start": 283,
    "end": 286
  },
  {
    "w": "those",
    "start": 287,
    "end": 292
  },
  {
    "w": "lyrics?",
    "start": 293,
    "end": 300
  },
  {
    "w": "Rot",
    "start": 301,
    "end": 304
  },
  {
    "w": "hooted",
    "start": 305,
    "end": 311
  },
  {
    "w": "ow,",
    "start": 312,
    "end": 315
  },
  {
    "w": "bave",
    "start": 316,
    "end": 320
  },
  {
    "w": "no",
    "start": 321,
    "end": 323
  },
  {
    "w": "bones!",
    "start": 324,
    "end": 330
  },
  {
    "w": "Sheer",
    "start": 331,
    "end": 336
  },
  {
    "w": "genius?",
    "start": 337,
    "end": 344
  },
  {
    "w": "the",
    "start": 345,
    "end": 348
  },
  {
    "w": "to",
    "start": 349,
    "end": 351
  },
  {
    "w": "con",
    "start": 352,
    "end": 355
  },
  {
    "w": "the",
    "start": 356,
    "end": 359
  },
  {
    "w": "son",
    "start": 360,
    "end": 363
  },
  {
    "w": "mate",
    "start": 364,
    "end": 368
  },
  {
    "w": "co",
    "start": 369,
    "end": 371
  },
  {
    "w": "Like",
    "start": 372,
    "end": 376
  },
  {
    "w": "P",
    "start": 377,
    "end": 378
  },
  {
    "w": "Ten",
    "start": 379,
    "end": 382
  },
  {
    "w": "gaspet",
    "start": 383,
    "end": 389
  },
  {
    "w": "bac",
    "start": 390,
    "end": 393
  },
  {
    "w": "like",
    "start": 394,
    "end": 398
  },
  {
    "w": "to,",
    "start": 399,
    "end": 402
  },
  {
    "w": "he",
    "start": 403,
    "end": 405
  },
  {
    "w": "had",
    "start": 406,
    "end": 409
  },
  {
    "w": "tum",
    "start": 410,
    "end": 413
  },
  {
    "w": "each",
    "start": 414,
    "end": 418
  },
  {
    "w": "needed",
    "start": 419,
    "end": 425
  },
  {
    "w": "to",
    "start": 426,
    "end": 428
  },
  {
    "w": "express",
    "start": 429,
    "end": 436
  },
  {
    "w": "his",
    "start": 437,
    "end": 440
  },
  {
    "w": "feelings.",
    "start": 441,
    "end": 450
  },
  {
    "w": "sam",
    "start": 451,
    "end": 454
  },
  {
    "w": "into",
    "start": 455,
    "end": 459
  },
  {
    "w": "the",
    "start": 460,
    "end": 463
  },
  {
    "w": "water,",
    "start": 464,
    "end": 470
  },
  {
    "w": "Tumbs,",
    "start": 471,
    "end": 477
  },
  {
    "w": "Rot",
    "start": 478,
    "end": 481
  },
  {
    "w": "said",
    "start": 482,
    "end": 486
  },
  {
    "w": "r",
    "start": 487,
    "end": 488
  },
  {
    "w": "some",
    "start": 489,
    "end": 493
  },
  {
    "w": "oxygen",
    "start": 494,
    "end": 500
  },
  {
    "w": "into",
    "start": 501,
    "end": 505
  },
  {
    "w": "their",
    "start": 506,
    "end": 511
  },
  {
    "w": "nice",
    "start": 512,
    "end": 516
  },
  {
    "w": "touch,",
    "start": 517,
    "end": 523
  },
  {
    "w": "if",
    "start": 524,
    "end": 526
  },
  {
    "w": "I",
    "start": 527,
    "end": 528
  },
  {
    "w": "say",
    "start": 529,
    "end": 532
  },
  {
    "w": "so",
    "start": 533,
    "end": 535
  },
  {
    "w": "myself",
    "start": 536,
    "end": 542
  },
  {
    "w": "grinned",
    "start": 543,
    "end": 550
  },
  {
    "w": "Tambon",
    "start": 551,
    "end": 557
  },
  {
    "w": "..and",
    "start": 558,
    "end": 563
  },
  {
    "w": "did",
    "start": 564,
    "end": 567
  },
  {
    "w": "you",
    "start": 568,
    "end": 571
  },
  {
    "w": "get",
    "start": 572,
    "end": 575
  },
  {
    "w": "chose",
    "start": 576,
    "end": 581
  },
  {
    "w": "lose",
    "start": 582,
    "end": 586
  },
  {
    "w": "Rot",
    "start": 587,
    "end": 590
  },
  {
    "w": "boorst",
    "start": 591,
    "end": 597
  },
  {
    "w": "buses,",
    "start": 598,
    "end": 604
  },
  {
    "w": "you",
    "start": 605,
    "end": 608
  },
  {
    "w": "knem,",
    "start": 609,
    "end": 614
  },
  {
    "w": "bave",
    "start": 615,
    "end": 619
  },
  {
    "w": "me",
    "start": 620,
    "end": 622
  },
  {
    "w": "benes!\"",
    "start": 623,
    "end": 630
  },
  {
    "w": "Sheee",
    "start": 631,
    "end": 636
  },
  {
    "w": "genius!",
    "start": 637,
    "end": 644
  },
  {
    "w": "ong's",
    "start": 645,
    "end": 650
  },
  {
    "w": "going",
    "start": 651,
    "end": 656
  },
  {
    "w": "to",
    "start": 657,
    "end": 659
  },
  {
    "w": "be",
    "start": 660,
    "end": 662
  },
  {
    "w": "the",
    "start": 663,
    "end": 666
  },
  {
    "w": "bit",
    "start": 667,
    "end": 670
  },
  {
    "w": "of",
    "start": 671,
    "end": 673
  },
  {
    "w": "the",
    "start": 674,
    "end": 677
  },
  {
    "w": "showt",
    "start": 678,
    "end": 683
  },
  {
    "w": "nboo",
    "start": 684,
    "end": 688
  },
  {
    "w": "guffawed",
    "start": 689,
    "end": 697
  },
  {
    "w": "and",
    "start": 698,
    "end": 701
  },
  {
    "w": "hit",
    "start": 702,
    "end": 705
  },
  {
    "w": "watched",
    "start": 706,
    "end": 713
  },
  {
    "w": "in",
    "start": 714,
    "end": 716
  },
  {
    "w": "dickelet",
    "start": 717,
    "end": 725
  },
  {
    "w": "let",
    "start": 726,
    "end": 729
  },
  {
    "w": "thé",
    "start": 730,
    "end": 733
  },
  {
    "w": "dir",
    "start": 734,
    "end": 737
  },
  {
    "w": "out",
    "start": 738,
    "end": 741
  },
  {
    "w": "of",
    "start": 742,
    "end": 744
  },
  {
    "w": "the",
    "start": 745,
    "end": 748
  },
  {
    "w": "taffatable",
    "start": 749,
    "end": 759
  },
  {
    "w": "ho",
    "start": 760,
    "end": 762
  },
  {
    "w": "asped",
    "start": 763,
    "end": 768
  },
  {
    "w": "but",
    "start": 769,
    "end": 772
  },
  {
    "w": "tike",
    "start": 773,
    "end": 777
  },
  {
    "w": "Ba",
    "start": 778,
    "end": 780
  },
  {
    "w": "Had",
    "start": 781,
    "end": 784
  },
  {
    "w": "fan",
    "start": 785,
    "end": 788
  },
  {
    "w": "at",
    "start": 789,
    "end": 791
  },
  {
    "w": "Rot",
    "start": 792,
    "end": 795
  },
  {
    "w": "h",
    "start": 796,
    "end": 797
  },
  {
    "w": "some",
    "start": 798,
    "end": 802
  },
  {
    "w": "Sheer",
    "start": 803,
    "end": 808
  },
  {
    "w": "senten",
    "start": 809,
    "end": 815
  },
  {
    "w": "get",
    "start": 816,
    "end": 819
  },
  {
    "w": "those",
    "start": 820,
    "end": 825
  },
  {
    "w": "lyrics?",
    "start": 826,
    "end": 833
  },
  {
    "w": "Rot",
    "start": 834,
    "end": 837
  },
  {
    "w": "hooted.",
    "start": 838,
    "end": 845
  },
  {
    "w": "W,",
    "start": 846,
    "end": 848
  },
  {
    "w": "have",
    "start": 849,
    "end": 853
  },
  {
    "w": "no",
    "start": 854,
    "end": 856
  },
  {
    "w": "bones\"",
    "start": 857,
    "end": 863
  },
  {
    "w": "Sheer",
    "start": 864,
    "end": 869
  },
  {
    "w": "genius!",
    "start": 870,
    "end": 877
  },
  {
    "w": ",",
    "start": 878,
    "end": 879
  },
  {
    "w": "be",
    "start": 880,
    "end": 882
  },
  {
    "w": "the",
    "start": 883,
    "end": 886
  },
  {
    "w": "hit",
    "start": 887,
    "end": 890
  },
  {
    "w": "of",
    "start": 891,
    "end": 893
  },
  {
    "w": "the",
    "start": 894,
    "end": 897
  },
  {
    "w": "show!",
    "start": 898,
    "end": 903
  },
  {
    "w": "a",
    "start": 904,
    "end": 905
  },
  {
    "w": "Tri",
    "start": 906,
    "end": 909
  },
  {
    "w": "watched",
    "start": 910,
    "end": 917
  },
  {
    "w": "in",
    "start": 918,
    "end": 920
  },
  {
    "w": "disbelief",
    "start": 921,
    "end": 930
  }
]


def get_word_at_offset(char_offset: int) -> int:
    """Finds word index corresponding to character offset in MERGED_TEXT."""
    for i, w in enumerate(WORDS):
        if w["start"] <= char_offset < w["end"]:
            return i
    return -1


def get_next_word_index(current_idx: int) -> int:
    """Returns next word index, bounded by total word count."""
    if current_idx + 1 < len(WORDS):
        return current_idx + 1
    return len(WORDS) - 1
